# Generated by Django 3.0.4 on 2020-04-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tile',
            new_name='title',
        ),
    ]
