# Generated by Django 3.0.4 on 2020-04-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200401_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.TextField(default=''),
        ),
    ]
